[mysql]
    [mysql.master]
        Host = "111"
        Database = "item"
        User = "item"
        Password = "111"
        Port = 3306
        MaxIdleConn = 1000
        MaxOpenConn = 2000
        SqlLog = false
