[mysql]
    [mysql.master]
        driver_name = "mysql"
        host = "localhost"
        database = "item"
        user = "item"
        password = "onp"
        port = 3306
        max_idle_conn = 1000
        max_open_conn = 2000
        conn_max_idle_time=60
        conn_max_life_time=3600
        sql_log = 4